"""Part 4 screen specifications (desktop web). Keys are P-IDs from sds_screens.SCREENS (section != '—').

Prose is English; quoted strings are the exact Vietnamese UI copy rendered by the app.

states:       (State, When it appears, draw.io frame name or 'N/A' / note)
layout:       ASCII zone sketch (brown code box, as in the template)
zones:        (Zone letter, description) — letters match the zone badges in the draw.io frames
interactions: (User action, What happens, Notes)
"""

SPECS = {}

SPECS["P-01"] = dict(
    purpose="Email + password sign-in for Guests. After sign-in the user goes to the route that was blocked before (state.from) or to /learn.",
    states=[("Loading", "Request in flight (button “Đang xử lý…”, disabled)", "P-01 / Loading"),
            ("Empty", "N/A — the form is always shown", "N/A"),
            ("Populated — default", "Form ready", "P-01 / Populated"),
            ("Error", "Wrong credentials / network error — HttpError message or “Không thể xác thực. Vui lòng thử lại.”", "P-01 / Error")],
    layout=["┌───────────────────────────────────────────────────────────┐",
            "│ SiteNavbar (Guest, [Đăng nhập][Đăng ký] hidden)           │",
            "├───────────────────────────┬───────────────────────────────┤",
            "│ [A] IELTS SPACE           │ [A] IELTS SPACE               │",
            "│ Mỗi ngày một bước. Gần    │     Chào mừng bạn trở lại     │",
            "│ hơn band mục tiêu.        │ [B] Email / Mật khẩu          │",
            "│ mascot + particles        │     Quên mật khẩu?            │",
            "│                           │ [C] [ Đăng nhập ] · hoặc ·    │",
            "│                           │     [Google (chưa hỗ trợ)]    │",
            "│                           │ [D] Chưa có tài khoản? Đăng ký│",
            "├───────────────────────────┴───────────────────────────────┤",
            "│ SiteFooter                              (Tư vấn miễn phí) │",
            "└───────────────────────────────────────────────────────────┘"],
    zones=[("A", "Ambient copy on the left (“Mỗi ngày một bước. Gần hơn band mục tiêu.” / “Giữ bài học, lộ trình và từ vựng trong một không gian tập trung.”) and the form header: “IELTS SPACE”, “Chào mừng bạn trở lại”, “Đăng nhập để tiếp tục lộ trình IELTS của bạn.”"),
           ("B", "Email (placeholder name@example.com) and Mật khẩu (placeholder “Mật khẩu”, show/hide toggle); right-aligned link “Quên mật khẩu?”."),
           ("C", "Primary button “Đăng nhập” (loading “Đang xử lý…”), “hoặc” divider, disabled “Google (chưa hỗ trợ)” button, role=status message area."),
           ("D", "“Chưa có tài khoản? Đăng ký ngay” → P-02.")],
    interactions=[("Submit valid credentials", "Session created; navigate (replace) to state.from or /learn (P-30)", "FT-02; GuestOnly"),
                  ("Submit wrong email/password", "role=status message; email kept", "Form is not cleared"),
                  ("Click “Quên mật khẩu?”", "→ P-03", ""),
                  ("Click Google", "Disabled; with the flag on it would start the provider flow (P-05)", "FT-05 Draft")],
)

SPECS["P-02"] = dict(
    purpose="Create a Learner account (full name, email, 6–72 character password). On success the user is signed in automatically.",
    states=[("Loading", "Registering (“Đang xử lý…”)", "Same layout as P-01 / Loading"),
            ("Empty", "N/A", "N/A"),
            ("Populated — default", "Registration form", "P-02 / Populated"),
            ("Error", "Mismatch “Mật khẩu xác nhận không khớp.” / length “Mật khẩu phải có từ 6 đến 72 ký tự.” / email already used (server message)", "P-02 / Error")],
    layout=["┌───────────────────────────────┐",
            "│ [A] BẮT ĐẦU HỌC               │",
            "│     Tạo tài khoản mới         │",
            "│ [B] Họ và tên · Email         │",
            "│     Mật khẩu · Xác nhận       │",
            "│ [C] [ Tạo tài khoản ]         │",
            "│     hoặc · [Google]           │",
            "│ [D] Đã có tài khoản? Đăng nhập│",
            "└───────────────────────────────┘",
            "(inside AuthShell, same as P-01)"],
    zones=[("A", "“BẮT ĐẦU HỌC” · “Tạo tài khoản mới” · “Bắt đầu kế hoạch học IELTS phù hợp với bạn.”"),
           ("B", "Họ và tên (Nguyễn Văn A), Email, Mật khẩu + hint “Từ 6 đến 72 ký tự.”, Xác nhận mật khẩu (“Nhập lại mật khẩu”)."),
           ("C", "“Tạo tài khoản” button, disabled Google button, status area."),
           ("D", "“Đã có tài khoản? Đăng nhập” → P-01.")],
    interactions=[("Submit valid form", "registerWithPassword → session → navigate to state.from or /learn", "FT-01"),
                  ("Confirmation differs", "Blocked client-side, message shown", ""),
                  ("Email already exists", "Message mapped from the HTTP error", "mapAuthPasswordHttpError")],
)

SPECS["P-03"] = dict(
    purpose="Request a password reset code by email without revealing whether the email exists.",
    states=[("Loading", "“Đang gửi…”", "N/A (button disabled)"),
            ("Populated — default", "Single email field", "P-03 / Populated"),
            ("Success", "Sent: “Nếu email tồn tại, mã đặt lại đã được tạo. (Môi trường demo: lấy mã từ log/Swagger BE.)”; button becomes “Gửi lại mã”", "P-03 / Success"),
            ("Error", "“Không gửi được yêu cầu. Thử lại.”", "Status area as in P-03 / Success")],
    layout=["┌────────────────────────────────┐",
            "│ [A] IELTS SPACE · Quên mật khẩu│",
            "│ [B] Email                      │",
            "│ [C] [ Gửi mã đặt lại ]  status │",
            "│ [D] Tôi đã có mã … · Quay lại  │",
            "└────────────────────────────────┘"],
    zones=[("A", "Ambient “Quên mật khẩu? Khôi phục nhanh.”; header “Quên mật khẩu” / “Chúng tôi sẽ xử lý mã đặt lại cho email của bạn.”"),
           ("B", "Email (name@example.com)."), ("C", "“Gửi mã đặt lại” → “Gửi lại mã”; role=status message."),
           ("D", "After sending: “Tôi đã có mã — đặt lại mật khẩu” (→ P-04) · “Quay lại đăng nhập” (→ P-01).")],
    interactions=[("Submit email", "Generic message, stays on the page", "FT-04; no account enumeration"),
                  ("“Tôi đã có mã”", "→ P-04", ""), ("“Quay lại đăng nhập”", "→ P-01", "")],
)

SPECS["P-04"] = dict(
    purpose="Set a new password with a reset code (typed in, not read from the URL).",
    states=[("Loading", "“Đang xử lý…”", "N/A"),
            ("Populated — default", "Code + password form", "P-04 / Populated"),
            ("Success", "“Đặt lại mật khẩu thành công. Đang chuyển tới đăng nhập…”, then automatic redirect to P-01 after ~0.9 s", "P-04 / Success"),
            ("Error", "“Không đặt lại được mật khẩu. Kiểm tra mã và thử lại.” or length / mismatch errors", "P-04 / Error")],
    layout=["┌────────────────────────────────┐",
            "│ [A] Đặt lại mật khẩu           │",
            "│ [B] Mã đặt lại · Mật khẩu mới  │",
            "│     Xác nhận mật khẩu          │",
            "│ [C] [ Đặt lại mật khẩu ]       │",
            "│ [D] Chưa có mã? Yêu cầu lại ·  │",
            "│     Đăng nhập                  │",
            "└────────────────────────────────┘"],
    zones=[("A", "“Đặt lại mật khẩu” · “Nhập mã xác nhận và mật khẩu mới.”"),
           ("B", "Mã đặt lại (“Dán mã từ log/Swagger hoặc email”), Mật khẩu mới (6–72), Xác nhận (“Nhập lại mật khẩu mới”)."),
           ("C", "“Đặt lại mật khẩu” button, status."), ("D", "“Chưa có mã? Yêu cầu lại” (→ P-03) · “Đăng nhập” (→ P-01).")],
    interactions=[("Submit valid form", "Success message → P-01", "FT-04"),
                  ("Wrong / expired code", "Error message; input kept", ""), ("“Yêu cầu lại”", "→ P-03", "")],
)

SPECS["P-10"] = dict(
    purpose="Public landing page for The IELTS Space; leads to practice tests, mentors and the plans / activation key table.",
    states=[("Loading", "Learner: “Đang tải thông tin gói hiện tại…” in the plans block", "Inside P-10 / Populated · Learner"),
            ("Empty", "N/A (static content)", "N/A"),
            ("Populated — Guest", "Hero + introduction + features + commitments + teachers + feedback + plans", "P-10 / Populated"),
            ("Populated — Learner", "Learner navbar; “Đang sử dụng · FREE” block or the not-connected notice", "P-10 / Populated · Learner"),
            ("Error", "“Chưa thể tải thông tin gói hiện tại.” + “Thử tải lại”", "Zone D")],
    layout=["┌─────────────────────────────────────────────┐",
            "│ SiteNavbar (Trang chủ active)               │",
            "├─────────────────────────────────────────────┤",
            "│ [A] Hero: tag · H1 · lead · 2 CTAs · 3 chips│",
            "│ [B] Introduction: image | THE IELTS SPACE … │",
            "│ [C] 4 features · commitments · teachers     │",
            "│     · learner feedback carousel             │",
            "│ [D] BẢNG GÓI DỊCH VỤ & KÍCH HOẠT MÃ         │",
            "│     FREE · Premium (30/90 days) · Points    │",
            "├─────────────────────────────────────────────┤",
            "│ SiteFooter                                  │",
            "└─────────────────────────────────────────────┘"],
    zones=[("A", "Tag “KHÔNG GIAN HỌC IELTS CỦA BẠN”; H1 “Mỗi ngày một bước. Gần hơn band mục tiêu.”; CTAs “Khám phá bài luyện →” (/practice-tests) and “Gặp gỡ Mentor →” (#home-mentors); chips ✓ 4 kỹ năng · Lộ trình rõ ràng · Học theo nhịp riêng."),
           ("B", "Introduction “THE IELTS SPACE KHÔNG GIAN HỌC TẬP TÍCH HỢP THẾ HỆ MỚI” + “Xem thêm về The IELTS Space →” (#home-features)."),
           ("C", "“TỐI ƯU HÀNH TRÌNH HỌC & LUYỆN THI IELTS” (4 cards), commitments 01–03, teachers + “Xem hồ sơ chuyên gia” (→ P-23), feedback carousel with “Tạm dừng / Tiếp tục chạy”."),
           ("D", "Plans: Gói FREE mặc định, Gói Premium (Premium 30 Ngày / 90 Ngày), Thẻ nạp Point (50 / 100); each product opens P-10c.")],
    interactions=[("“Khám phá bài luyện”", "→ /practice-tests; a Guest is redirected to P-01 (from)", "F-04"),
                  ("“Gặp gỡ Mentor”", "Scrolls to #home-mentors", ""),
                  ("“Kích hoạt” / “Nạp Key”", "Opens P-10c with the chosen product; focus returns to the button on close", "FT-11"),
                  ("“Thử tải lại” (plans error)", "Reloads the subscription", "Learner")],
)

SPECS["P-10c"] = dict(
    purpose="Dialog to activate a Premium plan or top up Points with an Activation Key.",
    states=[("Populated — default", "A product is selected", "P-10c / Populated"),
            ("Loading", "“Đang kích hoạt…”", "Zone C button disabled"),
            ("Success", "“Kích hoạt thành công” + “Hoàn tất” button", "Replaces zones B/C"),
            ("Error", "“Vui lòng nhập mã kích hoạt.” / “Chưa xác nhận được kết quả kích hoạt. Hãy giữ nguyên mã và thử lại khi kết nối ổn định.”", "Below the key field"),
            ("Guest", "“Đăng nhập tài khoản của bạn để kích hoạt gói hoặc nạp điểm.” + “Đăng nhập”", "P-10c / Populated (note)"),
            ("Unavailable", "Demo Learner session: “Phiên đăng nhập demo chưa hỗ trợ kích hoạt Key…” (see Appendix B G-04)", "P-10c / Populated (note)")],
    layout=["┌──────────────────────────────┐",
            "│ [A] Kích hoạt Gói / Nạp Key x│",
            "│     selected product         │",
            "│ [B] Mã Activation Key        │",
            "│ [C] [Kích hoạt bằng Mã Key]  │",
            "└──────────────────────────────┘"],
    zones=[("A", "Title “Kích hoạt Gói / Nạp Key”, close button, selected product."),
           ("B", "Field “Mã Activation Key” + description “Nhập đầy đủ mã được cấp, bao gồm tiền tố …”."),
           ("C", "“Kích hoạt bằng Mã Key” button; or the sign-in block (Guest) / demo notice.")],
    interactions=[("Enter a key and activate", "Calls the access API; on success the plans block on P-10 refreshes", "FT-11, FT-12"),
                  ("Guest clicks “Đăng nhập”", "→ P-01", ""), ("Close", "Dialog closes, focus restored", "")],
)

SPECS["P-30"] = dict(
    purpose="Course catalogue by band (index of /learn). Highlights the course in progress or the course recommended by the placement test.",
    states=[("Loading", "CourseCatalogSkeleton (“Đang tải danh sách khóa học…”)", "P-30 / Loading"),
            ("Empty", "Filter has no course: “Không tìm thấy khóa học” / “Không có khóa học nào trong nhóm này.” + “Xem tất cả khóa học”", "P-30 / Empty"),
            ("Populated — default", "Spotlight + course grid + placement card", "P-30 / Populated"),
            ("Error", "“Chưa tải được nội dung” + “Thử lại”; PLACEMENT_REQUIRED redirects to P-30a instead", "P-30 / Error")],
    layout=["┌───────────────────────────────────────────────────┐",
            "│ SiteNavbar · subnav (Test đầu vào … | Khóa học)   │",
            "├───────────────────────────────────────────────────┤",
            "│ [A] KHÓA HỌC · Lộ trình IELTS theo band mục tiêu  │",
            "│ [B] Spotlight: Band 6.0 | Đang học dở | 3/8 chặng │",
            "│     [ Học tiếp → ]                       mascot   │",
            "│ [C] Tất cả khóa học     (Tất cả|Gợi ý|Đang học|…) │",
            "│     [card] [card] [card]   (3-column grid)        │",
            "│     [card] [D] [Chưa biết nên chọn band nào?]     │",
            "└───────────────────────────────────────────────────┘"],
    zones=[("A", "Eyebrow “Khóa học”, H1 “Lộ trình IELTS theo band mục tiêu”, lead “Mỗi khóa gồm các chặng topic ngắn…”."),
           ("B", "Spotlight: the course in progress (label “Đang học dở”) or the suggested course (“Gợi ý cho bạn” / “Gợi ý bắt đầu”); band ticket; meta “{n} chặng topic · đầu vào khuyến nghị ~{band-1} · kết thúc bằng bài thi cuối khóa”; progress “x/y chặng”; CTA depends on status."),
           ("C", "Section “Tất cả khóa học” + segment filter (only tabs with data, with counts); course cards: band pill, chip (Đã hoàn thành / Sẵn sàng thi cuối / Đang học / Gợi ý cho bạn), title, meta, progress or “Chưa bắt đầu”, CTA (“Xem lại lộ trình”, “Làm bài thi cuối khóa”, “Học tiếp”, “Bắt đầu học”). Sorted by bandLevel."),
           ("D", "PlacementCard (only on the Tất cả tab): “Chưa biết nên chọn band nào?” · “Làm bài test đầu vào 4 kỹ năng miễn phí trong 15–20 phút…” · “Làm test đầu vào →”.")],
    interactions=[("Click a card / spotlight", "→ P-30b /learn/courses/:courseId", "FT-20"),
                  ("Choose a segment", "Client-side filter; no match → Empty state", ""),
                  ("Click the PlacementCard", "Currently → /placement (404); should be P-30a", "Appendix B G-01"),
                  ("API returns PLACEMENT_REQUIRED", "Redirect to /learn/placement with a notice", "BR-36, BR-40")],
)

SPECS["P-30a"] = dict(
    purpose="One-time four-skill placement test: goal survey → test (hub + exam shell) → grading → report and course recommendation.",
    states=[("Loading", "“Đang tải bài kiểm tra đầu vào…” / “Đang tải đề…” / “Đang tải báo cáo…”", "LoadingState (as the P-91 panel)"),
            ("Survey", "No usable attempt — 3 chat-style questions", "P-30a / Survey"),
            ("Survey Summary", "Target band chosen", "P-30a / Survey Summary"),
            ("Test Hub", "Attempt IN_PROGRESS", "P-30a / Test Hub"),
            ("Exam — Reading / Listening", "An objective section is open", "P-30a / Exam — Reading / Listening"),
            ("Exam — Writing", "Writing Task 1/2 section is open", "P-30a / Exam — Writing"),
            ("Exam — Speaking", "Speaking section is open", "P-30a / Exam — Speaking"),
            ("Grading", "Submitted; polling until a band exists", "P-30a / Grading"),
            ("Result Report", "Result available", "P-30a / Result Report"),
            ("Empty", "“Chưa có bài kiểm tra đầu vào nào được mở. Hãy quay lại sau.” / “Đề này chưa có câu hỏi.”", "lp-empty text"),
            ("Error", "ApiErrorState; submit failure “… Hãy thử nộp lại.” + “Thử nộp lại”", "Test Hub footer")],
    layout=["┌──────────────────────────────────────────────────┐",
            "│ [A] Stepper: Khảo sát - Bài test - Kết quả       │",
            "├──────────────────────────────────────────────────┤",
            "│ Survey: mascot + question bubble; chips/options  │",
            "│ Hub:  [B] elapsed clock | [C] sections (5 rows)  │",
            "│       [D] Làm lại khảo sát                       │",
            "│ Exam shell (full screen): top bar · part · body  │",
            "│       · question bar + [v] Nộp phần này          │",
            "│ Report: [B] current band > target [C] feasibility│",
            "│         [D] per-skill analysis [E] course list   │",
            "└──────────────────────────────────────────────────┘"],
    zones=[("A", "PlacementStepper “Khảo sát / Bài test / Kết quả”; connectors fill with progress (survey answers, sections submitted)."),
           ("B", "Survey: 3 questions “Bạn dự định thi IELTS khi nào?” (Tháng m/yyyy ×6, “Thời gian khác 📅”, “Chưa có kế hoạch”) · “Bạn có thể dành bao nhiêu thời gian học mỗi ngày?” (Dưới 1 tiếng … Trên 3 tiếng) · “Mục tiêu điểm IELTS của bạn là?” (Dưới IELTS 5.5 … 8.0 trở lên); “← Câu trước”. Hub: card “Bài kiểm tra đầu vào” — “Bạn đã bắt đầu được” Giờ/Phút/Giây + no-time-limit note."),
           ("C", "Summary dialog: “Bạn đã hoàn thành khảo sát!”, exam month, ~h/week, target band chart, “Tiếp tục”. Hub: “Phần thi của bạn” — Listening, Reading, Writing Task 1, Writing Task 2, Speaking; each row shows question count or minutes spent, button “Làm bài” / “Làm tiếp” (disabled once submitted); footer “Làm lần lượt từng phần. Bài được nộp tự động khi bạn hoàn thành phần cuối cùng.”"),
           ("D", "Hub: “Làm lại khảo sát”. Exam: question bar (numbered, answered in Primary, “x of n”) + ✓ “Nộp phần này” → dialog “Nộp phần Reading?” (“Bạn còn N câu chưa trả lời…”, “Làm tiếp” / “Nộp phần này”). Writing: Word count x/150, Mở bài / Thân bài / Kết bài, “Hoàn thành”, “Tra từ vựng” panel (Tra Việt-Anh / Tra Anh-Việt). Speaking: Hướng dẫn chung → Kiểm tra micro → each question (“Dừng & sang câu tiếp”). Report: per-skill analysis."),
           ("E", "Report: “Lộ trình khóa học” — one card per course with badge “Đề xuất cho bạn” / “Ôn nền tảng” / “Nâng cao”, CTA “Bắt đầu học” / “Xem khóa học” → P-30b.")],
    interactions=[("Pick a survey answer", "Next question; question 3 saves the Learning Goal (failure only warns)", "FT-09"),
                  ("“Tiếp tục” (summary)", "Creates a PLACEMENT_TEST attempt (or resumes the existing one) → Hub", "FT-35"),
                  ("Open a section", "Opens the exam shell and records the section start (startAttemptSection)", "Answers saved on blur"),
                  ("✕ in the exam shell", "Save and return to the Hub; unsubmitted sections can be reopened", ""),
                  ("Submit the last section", "completeSection → automatic submitAttempt → Grading", "Submitted sections cannot be reopened"),
                  ("Grading", "Polls GET /courses every 2 s, up to 45 times; success → Report", "“Đang chấm bài của bạn…”"),
                  ("“Bắt đầu học” (recommended course)", "→ P-30b", "BR-36")],
)

SPECS["P-30b"] = dict(
    purpose="Topic route inside one course; opens the next topic and the course final test.",
    states=[("Loading", "TopicListSkeleton (“Đang tải lộ trình chặng học…”)", "P-30b / Loading"),
            ("Empty", "“Khóa này chưa có chặng nào.”", "P-30b / Empty / Error"),
            ("Populated — default", "Progress header + topic list + finish line", "P-30b / Populated"),
            ("Locked", "LOCKED topic: card is not a link, “🔒 {reason}”; a reason identical to the previous topic is visually hidden", "P-30b / Populated"),
            ("Error", "ApiErrorState + “Thử lại”; course-test start errors shown inline", "P-30b / Empty / Error")],
    layout=["┌──────────────────────────────────────────────────┐",
            "│ ← Tất cả khóa học                                │",
            "│ [A] Band 6.0 · Lộ trình khóa học  │ [B] 2/5 chặng│",
            "│     Khóa IELTS Band 6.0           │  ==- 40%     │",
            "│     lead                          │  Tiếp theo…  │",
            "│                                   │ [Học tiếp →] │",
            "│ [C] Các chặng   (Tất cả|Listening|Reading|…)     │",
            "│ [D] o Chặng 01 … v  o Chặng 03 (is-next)  # …    │",
            "│ [E] F Về đích — Bài thi cuối khóa                │",
            "└──────────────────────────────────────────────────┘"],
    zones=[("A", "Back “← Tất cả khóa học”; eyebrow “Band x.x · Lộ trình khóa học”; H1 course title; lead “Học lần lượt từng chặng. Hoàn thành các bài học và đạt bài kiểm tra chặng (từ 70%) để mở chặng tiếp theo.”"),
           ("B", "Progress panel “x/y chặng đã qua” + %; “Tiếp theo — Chặng n: {title}” + CTA “Học tiếp” / “Bắt đầu chặng”; or “Bạn đã qua tất cả các chặng.”"),
           ("C", "“Các chặng” + skill filter (Tất cả / Listening / Reading / Writing / Speaking — only when there is more than one skill)."),
           ("D", "Vertical route: node (number / ✓ / 🔒), kicker “Chặng 0n · Skill”, “👑 Premium” chip, title, description, footer (“Đã qua · n bài”, progress “x/y bài”, or lock reason), CTA “Vào chặng” / “Học tiếp” / “Xem lại”."),
           ("E", "“Về đích — Bài thi cuối khóa”: LOCKED “Mở khi qua đủ n chặng (hiện x/n). Cần đạt từ 70%.”; AVAILABLE “Bạn đã qua mọi chặng…” + “Làm bài thi cuối khóa” (“Đang giao đề…”); PASSED chip “Đã đạt”. Errors: “Bài thi cuối khóa chưa mở…” / “Chưa có đề thi cuối cho khóa này…”.")],
    interactions=[("Click an open topic", "→ P-31", "FT-20"),
                  ("Click a locked topic", "No navigation (aria-disabled, aria-describedby reason)", ""),
                  ("“Làm bài thi cuối khóa”", "createCourseTestAssignment + createAttempt COURSE_TEST → P-35 ?course=", "FT-55"),
                  ("Filter by skill", "Client-side filter, keeps sequenceOrder", "")],
)

SPECS["P-31"] = dict(
    purpose="Topic detail: lesson list, next step, unlock conditions and the start of the topic final test.",
    states=[("Loading", "“Đang tải chặng học…”", "LoadingState"),
            ("Empty", "“Chặng này chưa có bài học.”", "Text inside the section"),
            ("Populated — default", "An AVAILABLE lesson is next", "P-31 / Populated"),
            ("Locked test / Review gate", "Test LOCKED with checklist; a mandatory review turns the CTA into “Làm bài ôn”", "P-31 / Locked Test / Review Gate"),
            ("Error", "TOPIC_LOCKED → back to /learn with a notice; otherwise ApiErrorState", "—")],
    layout=["┌──────────────────────────────────────────────────┐",
            "│ (ReviewGateBanner)  ← {course title}             │",
            "│ [A] Chặng 03 · Reading — Matching Headings │ [B] │",
            "│ [C] Bài học trong chặng        3 bài · ~45 phút  │",
            "│     v Bài 1 …  o Bài 2 (next) …  # Bài 3 …       │",
            "│     └ Cần luyện thêm … Luyện ngay →              │",
            "│ [D] F Kiểm tra cuối chặng — checklist / CTA      │",
            "└──────────────────────────────────────────────────┘"],
    zones=[("A", "Back “← {course title}”; eyebrow “Chặng 0n · Skill”; H1 topic title; description."),
           ("B", "Panel: “x/y bài đã xong” + %; one of: “Cần làm trước — Bài ôn: …” + “Làm bài ôn”; “Bắt đầu với / Tiếp theo / Cần luyện thêm — Bài n: …” + “Bắt đầu học / Học tiếp / Luyện thêm”; “Đã học xong các bài. Làm bài kiểm tra chặng ↓”; “Bạn đã qua chặng này · x%”."),
           ("C", "“Bài học trong chặng” + “n bài · khoảng m phút”; each lesson: node, title, “🕒 m phút”, lock reason, CTA “Mở bài” / “Học tiếp” / “Xem lại”; extra row “Cần luyện thêm trước khi mở bài kiểm tra chặng — Luyện ngay” (→ P-33)."),
           ("D", "“Kiểm tra cuối chặng” — test title, meta “n câu hỏi · cần đạt từ 70% · không giới hạn thời gian · lần gần nhất x%”; LOCKED: “Để mở bài kiểm tra:” checklist with links; AVAILABLE: “Làm bài kiểm tra”; PASSED: “Đã đạt”; NONE: “Chặng này không có bài kiểm tra cuối.”")],
    interactions=[("Open a lesson", "→ P-32", "FT-21"), ("“Luyện ngay”", "→ P-33", "FT-27"), ("“Làm bài ôn”", "→ P-34", "FT-28"),
                  ("“Làm bài kiểm tra”", "createTestAssignment + createAttempt TOPIC_TEST → P-35 ?topic=", "FT-29"),
                  ("Test start fails", "PRACTICE_REQUIRED: “Cần luyện thêm trước khi mở đề: Bài n…”; REVIEW_REQUIRED; TEST_LOCKED; TEST_UNAVAILABLE “Chưa có đề cho chặng này…”", "role=alert")],
)

SPECS["P-32"] = dict(
    purpose="Study one lesson: content blocks (text, audio, passage, exercises, essay) and record completion.",
    states=[("Loading", "“Đang tải nội dung bài học…”", "LoadingState"),
            ("Populated — default", "Studying", "P-32 / Populated"),
            ("Completed", "Panel “Bạn đã hoàn thành bài này” / “Bài này đã hoàn thành”", "P-32 / Completed"),
            ("Review required", "REVIEW_REQUIRED: “Nội dung này đang tạm khóa” + “Làm bài ôn” / “Về danh sách bài”", "P-32 / Review Required"),
            ("Error", "Submit failure “… Hãy thử lại.”; essay: “Không đủ điểm…”, “Hệ thống chấm bài tạm thời không khả dụng…”, “Bạn đã hết hạn mức chấm bài trong ngày.”", "Inline in the block / rail")],
    layout=["┌───────────────────────────────────────┬──────────────┐",
            "│ ← {Topic}                             │ [D] Rail     │",
            "│ [A] Bài 2 · Lý thuyết và bài tập      │ Bài 2 · …    │",
            "│     H1 lesson title                   │ o Đang học   │",
            "│ [B] TextBlock / AudioBlock / Passage  │ hint         │",
            "│ [C] ExerciseBlock · EssayBlock        │ [Hoàn thành] │",
            "│ [E] Completion panel                  │ Danh sách bài│",
            "└───────────────────────────────────────┴──────────────┘"],
    zones=[("A", "Back to the topic; eyebrow “Bài n · Lý thuyết và bài tập” (or “Lý thuyết”); H1."),
           ("B", "BlockList: TextBlock, AudioBlock (player + transcript), PassageBlock; unsupported blocks render UnsupportedBlock."),
           ("C", "ExerciseBlock: questions + “Nộp” / “Nộp lại” / “Làm lại từ đầu”; result “Đạt x/y câu (z%)…” or “Đúng x/y câu… Cần từ 70% để đạt.”. EssayBlock: “Bài làm của bạn”, “Nộp bài · 3 điểm”, “Đang chấm (có thể 10–45 giây)…”, “Band ước lượng”, “Bài mẫu”, disclaimer “Band là ước lượng AI, không phải điểm IELTS chính thức.”"),
           ("D", "Sticky rail: status (Đang học / Cần làm bài ôn / Cần luyện thêm / Đã hoàn thành) + hint + CTA (“Hoàn thành bài” / “Đang ghi nhận…”, “Làm bài ôn”, “Luyện thêm bài này”, “Bài tiếp theo”, “Về chặng làm bài kiểm tra”) + link “Danh sách bài của chặng”."),
           ("E", "Completion panel: “Kiến thức của bài đã được ghi nhận…” / “Bài này yêu cầu luyện thêm…” / “Bạn đã học xong bài cuối của chặng…” + links “Luyện thêm bài này”, “Về danh sách bài”. Theory-only lessons: “Hết nội dung bài học. Bấm Hoàn thành bài để ghi nhận tiến độ.”")],
    interactions=[("Submit an exercise", "Graded; answers/explanations shown on pass", "FT-22, FT-23"),
                  ("Submit an essay", "Deducts 3 points, AI grading, band shown", "FT-25; INSUFFICIENT_POINTS"),
                  ("“Hoàn thành bài”", "completeLesson → Completed; may require extra practice", "FT-21"),
                  ("“Bài tiếp theo” / back to topic", "→ next P-32 / P-31", ""),
                  ("REVIEW_REQUIRED", "Content locked → P-34", "FT-28")],
)

SPECS["P-33"] = dict(
    purpose="Extra practice after a lesson: pick a practice set, answer and submit; passing at least one set unlocks the topic test.",
    states=[("Loading", "“Đang tải luyện thêm…”", "LoadingState"),
            ("Empty", "“Bài này không có bộ luyện thêm.”", "P-33 / Set List (note)"),
            ("Populated — Set list", "List of sets", "P-33 / Set List"),
            ("Attempt", "Working on one set", "P-33 / Attempt"),
            ("Outcome", "Passed / Not passed / Review created", "P-33 / Outcome"),
            ("Passed (overall)", "“Bạn đã đạt phần luyện thêm. Quay lại chặng để làm bài kiểm tra (nếu không còn bài ôn).” + “Về lộ trình”", "P-33 / Set List (note)")],
    layout=["┌──────────────────────────────────────────────────┐",
            "│ ← {Lesson}                                       │",
            "│ [A] LUYỆN THÊM · Củng cố trước khi mở bài KT     │",
            "│ [B] Bộ 1 [Đã thử] 10 câu · cao nhất 60% [Làm lại]│",
            "│     Bộ 2 [Sẵn sàng]                [Làm bộ này]  │",
            "│     Bộ 3 [Chưa mở] Premium         [Khóa]        │",
            "│ Attempt: [B] passage/audio | [C] ExerciseBlock   │",
            "│ Outcome: [D] passed [E] not passed [F] review    │",
            "└──────────────────────────────────────────────────┘"],
    zones=[("A", "Back to the lesson; eyebrow “Luyện thêm”; H1 “Củng cố trước khi mở bài kiểm tra chặng”; meta “Bắt buộc: đạt ít nhất một bộ để mở bài kiểm tra chặng” / “Đã đạt phần luyện thêm” + practicePassReason; “Hoàn thành bài học trước khi luyện.”"),
           ("B", "Set list: title, status chip (Sẵn sàng / Đang làm / Đã đạt / Đã thử / Chưa mở), “n câu · điểm cao nhất x%”, warnings “Đã lộ đáp án nên không được tính.” and “Bộ Premium, chưa mở trong giai đoạn này.”, CTA “Làm bộ này / Làm tiếp / Làm lại / Đang mở… / Khóa”. Attempt: “← Danh sách luyện thêm”, eyebrow “Luyện thêm · {code}”, audio/passage."),
           ("C", "ExerciseBlock without resubmission; instructions “Trả lời hết câu. Đạt mới được tính evidence cho practice của bài.”"),
           ("D", "“Đã đạt bộ luyện thêm (x%).” + “Tiếp tục luyện / về topic”."),
           ("E", "“Chưa đạt (x%). Có thể chọn bộ khác hoặc làm bài ôn nếu được tạo.” + “Về danh sách”."),
           ("F", "“Đã tạo bài ôn bắt buộc sau lần luyện này.” + “Làm bài ôn →” (P-34).")],
    interactions=[("“Làm bộ này”", "startPractice → Attempt", "FT-27"), ("“Nộp”", "Graded; may create a review", "FT-26, FT-28"),
                  ("“Làm bài ôn”", "→ P-34", ""), ("“Về danh sách”", "Reloads the catalogue", "")],
)

SPECS["P-34"] = dict(
    purpose="Mandatory review for a knowledge point: theory + quick check, then review sets until passed or attempts run out.",
    states=[("Loading", "“Đang tải bài ôn…”", "LoadingState"),
            ("Theory", "Stage THEORY — theory + quick check", "P-34 / Theory"),
            ("Practice set", "Stage PRACTICE_SET — review question set, “Số bộ chưa đạt: x/y”", "P-34 / Practice Set"),
            ("Finished", "DONE “Đã hoàn thành bài ôn” / SKIPPED “Đã bỏ qua bài ôn”", "P-34 / Finished"),
            ("Error", "Submit failure — inline", "—")],
    layout=["┌──────────────────────────────────────────────────┐",
            "│ ← Về lộ trình học                                │",
            "│ [A] BÀI ÔN BẮT BUỘC · Bước … — {knowledge point} │",
            "│ [D] Outcome panel (when finished)                │",
            "│ [B] Lý thuyết cần nhớ                            │",
            "│ [C] Kiểm tra nhanh lý thuyết | review set (split)│",
            "└──────────────────────────────────────────────────┘"],
    zones=[("A", "Back “Về lộ trình học”; eyebrow “Bài ôn bắt buộc · Bước đọc lý thuyết / luyện tập”; H1 knowledge point; lead depends on the stage."),
           ("B", "“Lý thuyết cần nhớ” — theory BlockList."),
           ("C", "THEORY: ExerciseBlock “Kiểm tra nhanh lý thuyết” (no questions → “Xác nhận đã đọc lý thuyết để sang bước luyện tập.” + “Tiếp tục luyện ôn”). PRACTICE_SET: audio/passage + set “Bộ x/y · {code}”; not passed → “Làm bộ tiếp theo”."),
           ("D", "DONE: “Lộ trình đã mở lại. Bạn có thể học tiếp.”; SKIPPED: “Bạn chưa đạt sau n bộ. Bài ôn được bỏ qua để bạn tiếp tục học.”; CTA “Học tiếp →”.")],
    interactions=[("Submit the quick check", "Moves to stage PRACTICE_SET", "FT-28"), ("Submit a review set", "Passed → DONE; not passed → next set", "FT-26"),
                  ("“Học tiếp”", "Back to the interrupted lesson/topic; the gate banner disappears", "")],
)

SPECS["P-35"] = dict(
    purpose="Take the topic final test (?topic=) or the course final test (?course=); answers are saved immediately; no time limit.",
    states=[("Loading", "“Đang tải đề…”", "LoadingState"),
            ("Empty", "“Đề này chưa có câu hỏi.”", "Text"),
            ("Populated — default", "Answering", "P-35 / Populated"),
            ("Confirm submit", "Blank answers on first submit: “Còn n câu bỏ trống, các câu đó sẽ tính sai. Bấm lần nữa để nộp.”", "P-35 / Confirm Submit"),
            ("Error", "“Chưa lưu được một số câu trả lời…” / “… Hãy thử nộp lại.”", "Footer bar")],
    layout=["┌──────────────────────────────────────────────────┐",
            "│ ← Về topic                                       │",
            "│ [A] BÀI KIỂM TRA CUỐI · Làm từng phần…  ∞        │",
            "│ [B] [Phần 1 4/10] [Phần 2 0/10] [Phần 3 0/5]     │",
            "│ [C] audio / passage   |  Phần 1/3 · questions    │",
            "│                       |  Đã lưu / Đang lưu…      │",
            "│ [D] 4/25 câu đã trả lời            [ > Nộp bài ] │",
            "└──────────────────────────────────────────────────┘"],
    zones=[("A", "Back “Về topic” / “Về khóa học”; eyebrow “Bài kiểm tra cuối” / “Thi cuối khóa”; H1 “Làm từng phần, câu trả lời được lưu ngay”; “Không giới hạn thời gian”."),
           ("B", "Section tabs (aria-current=step): “Phần n” + “x/y câu”."),
           ("C", "Split: section audio/passage | questions (QuestionField) + SaveIndicator “Đang lưu…”, “Đã lưu”, “Chưa lưu được, sẽ thử lại khi nộp”; “Phần trước / Phần tiếp”."),
           ("D", "Sticky bottom bar: “x/y câu đã trả lời”, warning, button “Nộp bài” → “Vẫn nộp bài” → “Đang nộp…”.")],
    interactions=[("Answer / blur", "Saves the response per question", "FT-30"), ("“Nộp bài” with blanks", "First click warns, second click submits", ""),
                  ("Submit succeeds", "Navigate (replace) → P-36 (keeps ?topic / ?course)", "FT-31"), ("“Về topic”", "→ P-31 / P-30b", "")],
)

SPECS["P-36"] = dict(
    purpose="Result of the topic / course final test: score, pass or fail, next step, per-question list.",
    states=[("Loading", "“Đang chấm bài…”", "LoadingState"),
            ("Passed", "≥ 70%", "P-36 / Passed"),
            ("Failed", "< 70% — answers hidden", "P-36 / Failed"),
            ("Error", "ApiErrorState + Thử lại", "—")],
    layout=["┌──────────────────────────────────────────────────┐",
            "│ [A] (85%) KẾT QUẢ · mã đề … — Đạt bài kiểm tra…  │",
            "│     17/20 câu đúng · 85% · cần từ 70%            │",
            "│ [B] [Sang chặng tiếp theo] [Xem danh sách khóa]  │",
            "│ [C] Từng câu: Câu 1 · prompt · correct/wrong …   │",
            "└──────────────────────────────────────────────────┘"],
    zones=[("A", "Score dial %, eyebrow “Kết quả · mã đề {code}”, H1 “Đạt bài kiểm tra cuối” / “Đạt thi cuối khóa” / “Chưa đạt lần này”, score line, message (see Appendix B G-02 about technical copy)."),
           ("B", "Passed: “Sang chặng tiếp theo” (when nextTopicId exists) or “Về khóa học” (course) + “Xem danh sách khóa”; failed: “Về topic để làm lại” / “Về khóa để làm lại”."),
           ("C", "“Từng câu” — number, prompt, status; correct answers only when passed.")],
    interactions=[("“Sang chặng tiếp theo”", "→ P-31 of the new topic", "FT-29"), ("“Về khóa học”", "→ P-30b", "FT-55"),
                  ("Retry", "→ P-31 / P-30b; the next attempt gets a different test code", ""), ("“Xem danh sách khóa”", "→ P-30", "")],
)

SPECS["P-41"] = dict(
    purpose="Catalogue of four-skill practice tests (mock data): filter by skill, source, status and search.",
    states=[("Loading", "N/A — static mock data", "N/A"),
            ("Empty", "No card matches the filters — empty grid (no dedicated copy yet)", "N/A"),
            ("Populated — default", "Sidebar + banner + tabs + card grid", "P-41 / Populated"),
            ("Error", "N/A (no API call yet)", "N/A")],
    layout=["┌──────────┬───────────────────────────────────────┐",
            "│ [A] LUYỆN│ [B] Chưa biết mình đang ở band nào?   │",
            "│ ĐỀ       │     > TEST NGAY                       │",
            "│ KỸ NĂNG  │ [C] (Bài chưa làm|Bài đã làm)  Tìm    │",
            "│ Reading^ │ [D] [card] [card] [card]  (3 columns) │",
            "│ NGUỒN …  │     [card] [card]                     │",
            "└──────────┴───────────────────────────────────────┘"],
    zones=[("A", "PracticeSidebar “LUYỆN ĐỀ · The IELTS Space”; “KỸ NĂNG”: Reading (Bài lẻ: Passage 1/2/3, Full đề), Listening, Writing, Speaking; “NGUỒN TÀI LIỆU”: The IELTS Space PRO [PRO], Actual Tests, Các nguồn khác."),
           ("B", "PracticeCosmicBanner “Chưa biết mình đang ở band nào?” / “Test đầu vào và khám phá trình độ IELTS hiện tại của bạn.” + “TEST NGAY ✦” (see G-03)."),
           ("C", "Tabs “Bài chưa làm” / “Bài đã làm”; search box “Tìm tên bài tập”."),
           ("D", "PracticeTestCard: image, ribbon MIỄN PHÍ / PRO, passage pill, title, question-type bullets; click / Enter / Space opens P-41a.")],
    interactions=[("Choose a skill (sidebar or ?skill=)", "Filters the cards", "The Luyện tập subnav keeps ?skill= in sync"),
                  ("Choose a card", "Opens P-41a", ""), ("Search", "Filters by title", "Client-side")],
)

SPECS["P-41a"] = dict(
    purpose="Choose the attempt mode for the selected card: exam simulation or practice.",
    states=[("Populated — default", "Thi thử selected by default", "P-41a / Populated")],
    layout=["┌────────────────────────────────────┐",
            "│ [A] {Test title}                 x │",
            "│ Lựa chọn chế độ làm bài            │",
            "│ [B] [Thi thử]        [Luyện tập]   │",
            "│ [C]      [ BẮT ĐẦU LÀM BÀI ]       │",
            "└────────────────────────────────────┘"],
    zones=[("A", "Test title (DialogTitle)."),
           ("B", "Two aria-pressed cards: “Thi thử” — “Tập trung như phòng thi thật. Không có Highlight, Note, tra từ hay Flashcard.”; “Luyện tập” — “Học chủ động với các hỗ trợ phù hợp cho từng kỹ năng và xem lại tiến độ của bạn.”"),
           ("C", "Button “BẮT ĐẦU LÀM BÀI”.")],
    interactions=[("Choose a mode", "Selected card changes", ""), ("“BẮT ĐẦU LÀM BÀI”", "reading → /practice/test/:id?mode=; others → /practice/{skill}/:id?mode=", "F-03"),
                  ("Close / Esc", "Back to P-41", "")],
)

SPECS["P-42"] = dict(
    purpose="Reading workspace: passage, question map and answers; practice mode adds Highlight / Note / dictionary / Flashcard tools.",
    states=[("Populated — Practice", "mode=practice", "P-42 / Practice Mode"),
            ("Populated — Exam", "mode=exam (Thi thử)", "P-42 / Exam Mode"),
            ("Feedback", "aria-live messages: “Hãy bôi đen một đoạn trong bài đọc trước khi chọn công cụ.”, “Đã Highlight đoạn được chọn.”, “Đã bỏ Highlight.”", "Inside the frame")],
    layout=["┌────────────────────────────────────────────────────┐",
            "│ [A] ← Thoát | Luyện tập 00:12:40 | Tiến độ | Ghi chú│",
            "├──────────┬───────────────────────┬─────────────────┤",
            "│ [B] Map  │ [C] Công cụ hỗ trợ    │ [E] Question 1/5│",
            "│ 1 2 3    │ [D] Snow Makers A–E   │ List of Headings│",
            "│ Back Next│     (highlight)       │ 1. Paragraph C  │",
            "└──────────┴───────────────────────┴─────────────────┘"],
    zones=[("A", "Sub-topbar: “← Thoát”, badge “Luyện tập / Thi thử”, timer, “Tiến độ x/5 câu” bar, “Ghi chú (n)” (practice), ⚙ “Cài đặt giao diện” (Chế độ bảo vệ mắt, Kích cỡ chữ)."),
           ("B", "QUESTION MAP “Bản đồ câu hỏi” 1–5 + Back / Next."),
           ("C", "PRACTICE TOOLS “Công cụ hỗ trợ”: Highlight, Note, Tra từ vựng, Tạo Flashcard, “Thẻ đã lưu”, “Bỏ Highlight” (practice mode only)."),
           ("D", "Passage “Snow Makers” paragraphs A–E; select text to act on it, right-click context menu."),
           ("E", "Matching Headings questions (List of Headings i–x, answer for Paragraph C…), ⚑ flag, “Đã chọn x/5 câu”.")],
    interactions=[("Select text + tool", "Highlight / open P-42d / P-42b / P-42a", "FT-42, FT-43"),
                  ("“Thẻ đã lưu”", "Opens P-42c", ""), ("Answer / ⚑", "Updates map and progress", "Not saved to the server"),
                  ("“Thoát”", "→ P-41", "")],
)

for pid, desc, zones, inter in (
    ("P-42a", "Save the selected word/phrase as a flashcard (localStorage, not synced to the account).",
     [("A", "“Tạo Flashcard” · “Lưu từ vựng và ảnh minh họa trên trình duyệt này. Chưa đồng bộ tài khoản.”"),
      ("B", "“Từ / cụm từ *” (prefilled), “Nghĩa / định nghĩa *”, “Ví dụ / ngữ cảnh”, “Ảnh minh họa” (PNG, JPG hoặc WebP · tối đa 1 MB)."),
      ("C", "Errors “Nhập từ vựng và nghĩa trước khi lưu.” / “Không lưu được: bộ nhớ đầy…”; button “Lưu Flashcard”.")],
     [("“Lưu Flashcard”", "Writes to localStorage; P-42 shows “Đã lưu Flashcard trên trình duyệt này. Mở “Thẻ đã lưu” để xem.”", "FT-43"), ("Close", "Back to P-42", "")]),
    ("P-42b", "Look up the selected word in the passage glossary; Wiktionary link.",
     [("A", "“Tra từ vựng” · “Từ điển nhỏ của bài đọc. Có thể tra cứu thêm trên Wiktionary.”"),
      ("B", "Selected word + meaning; not found: “Chưa có nghĩa trong từ điển của bài…”"), ("C", "Wiktionary link (new tab).")],
     [("Open Wiktionary", "New tab", "noopener"), ("Close", "Back to P-42", "")]),
    ("P-42c", "View flashcards saved in this browser.",
     [("A", "“Flashcard đã lưu (n)”."), ("B", "Card list (image, word, meaning, example); empty: “Chưa có thẻ. Chọn từ trong bài đọc và nhấn “Tạo Flashcard”.”; storage read errors use role=alert.")],
     [("Close", "Back to P-42", "")]),
    ("P-42d", "Draggable floating notes panel tied to the selected paragraph; kept for the session only.",
     [("A", "Draggable title bar (⠿), minimise —, hide ✕; “Kéo thanh tiêu đề để di chuyển”, move left/right buttons."),
      ("B", "Selected paragraph, “Nội dung ghi chú”, “Lưu ghi chú”, “Ghi chú giữ trong phiên làm bài; tải lại trang sẽ xóa.”"),
      ("C", "Note list (Đoạn n · time) + delete; empty: “Chưa có ghi chú. Chọn một đoạn văn và viết điều cần nhớ.”")],
     [("“Lưu ghi chú”", "Added at the top of the list; “Đã lưu ghi chú trong phiên làm bài này.”", "FT-42"), ("Drag / arrow keys", "Moves the panel", "a11y"),
      ("Hide", "Closes the panel, focus returns to the Ghi chú button", "")]),
):
    SPECS[pid] = dict(purpose=desc,
                      states=[("Populated — default", "Opened from P-42 (practice mode)", f"{pid} / Populated")],
                      layout=None, zones=zones, interactions=inter)

SPECS["P-43"] = dict(
    purpose="Listening workspace (mock): audio player, question map that follows audio cues, answer per question.",
    states=[("Populated — default", "Audio 03:06, 5 questions", "P-43 / Populated")],
    layout=["┌───────────────────────────────────────────────────────┐",
            "│ [A] ← Thoát | Listening · Section 1 · Practice        │",
            "│ [B] Map │ [C] player · SECTION 1 │ [D] Question 3 of 5│",
            "└───────────────────────────────────────────────────────┘"],
    zones=[("A", "“← Thoát”, Listening badge, “Section 1 · Practice”, progress."), ("B", "Question map 1–5 + Back/Next; follows the audio cue automatically."),
           ("C", "AudioPlayer (play/pause, seek, volume, speed) + “SECTION 1 · Student services enquiry” + instructions."),
           ("D", "Current question: prompt, helper “Write ONE word and/or a number.”, field “Nhập đáp án cho câu n”, ⚑.")],
    interactions=[("Play / seek", "Active question follows the cue", ""), ("Select a question", "Seeks to that question's cue", ""), ("“Thoát”", "→ P-41", "")],
)

SPECS["P-44"] = dict(
    purpose="Writing Task 1 workspace (mock): prompt + chart, essay editor with word count and countdown.",
    states=[("Populated — default", "Empty response", "P-44 / Populated")],
    layout=["┌───────────────────────────┬──────────────────────┐",
            "│ [A] ← Thoát · Writing · {title}                  │",
            "│ [B] WRITING PROMPT        │ [C] YOUR RESPONSE    │",
            "│     TASK VISUAL (chart)   │     textarea         │",
            "│     [Phóng to biểu đồ]    │     ≥150 từ · 0/150  │",
            "└───────────────────────────┴──────────────────────┘"],
    zones=[("A", "Topbar “← Thoát”, Writing badge, task title."), ("B", "Prompt + chart “Transport use in a European city” (Car / Bus / Bicycle) + “Phóng to biểu đồ” (P-44a)."),
           ("C", "“Write your answer”, CountdownTimer, textarea “Start writing your response here…”, “Mục tiêu: ít nhất 150 từ. Bài viết chỉ được giữ trong phiên hiện tại.”, WordCounter.")],
    interactions=[("Type", "Word count updates", "Not saved, not graded"), ("“Phóng to biểu đồ”", "Opens P-44a", ""), ("“Thoát”", "→ P-41", "")],
)

SPECS["P-44a"] = dict(
    purpose="View the Writing task chart at a large size.",
    states=[("Populated — default", "Opened from P-44", "P-44a / Populated")],
    layout=None,
    zones=[("A", "Chart title + close."), ("B", "Enlarged SVG chart (is-large).")],
    interactions=[("Close / Esc", "Back to P-44", "")],
)

SPECS["P-90"] = dict(
    purpose="Global 404 for undeclared routes.",
    states=[("Populated — default", "Any unmatched path", "P-90 / Populated")],
    layout=None,
    zones=[("A", "Icon, “404”, “Không tìm thấy trang”, “Không có màn hình nào được khai báo cho {pathname}.”"), ("B", "“Về Overview” (→ /overview; a Guest is sent to P-01 — G-05).")],
    interactions=[("“Về Overview”", "→ /overview", "")],
)
SPECS["P-91"] = dict(
    purpose="Not-found state inside /learn (unmatched child route or API NOT_FOUND); keeps the navbar and learn layout.",
    states=[("Populated — default", "Unmatched /learn/* / NOT_FOUND", "P-91 / Populated")],
    layout=None,
    zones=[("A", "“Không tìm thấy trang” / “Nội dung này không tồn tại hoặc đã bị gỡ.”"), ("B", "“Về lộ trình” → /learn.")],
    interactions=[("“Về lộ trình”", "→ P-30", "")],
)
SPECS["P-92"] = dict(
    purpose="Shared template for routes that exist but have no content yet (Stub).",
    states=[("Populated — default", "Every Stub route (P-22, P-23, P-40, P-51…P-54, P-70…P-72)", "P-92 / Populated")],
    layout=None,
    zones=[("A", "🚧 icon, “IELTSPATH”, route title (e.g. “Thực hành”, “Lịch sử nộp bài”), “Trang này đã có đường dẫn riêng nhưng nội dung vẫn đang được hoàn thiện.”"),
           ("B", "“Về Overview” (Primary) · “Đến lớp học” (outline).")],
    interactions=[("“Về Overview”", "→ /overview", "RequireAuth"), ("“Đến lớp học”", "→ /classroom (P-20)", "")],
)
